services:
  proxy:
    image: itzg/bungeecord
    container_name: mc-proxy
    ports:
      - "25565:25565" # Java Edition
      - "19132:19132/udp" # Bedrock Edition
      - "8081:8081" # Eaglercraft WebSockets
    environment:
      TYPE: WATERFALL
      ONLINE_MODE: "false"
    volumes:
      - ./proxy:/server
    restart: unless-stopped
    networks:
      - mc-network

  lobby:
    image: itzg/minecraft-server
    container_name: mc-lobby
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21"
      ONLINE_MODE: "false"
      MEMORY: "1G"
    volumes:
      - ./lobby:/data
    restart: unless-stopped
    networks:
      - mc-network

  fireball:
    image: itzg/minecraft-server
    container_name: mc-fireball
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21"
      ONLINE_MODE: "false"
      MEMORY: "2G"
    volumes:
      - ./fireball:/data
    restart: unless-stopped
    networks:
      - mc-network

  survival:
    image: itzg/minecraft-server
    container_name: mc-survival
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: "1.21"
      ONLINE_MODE: "false"
      MEMORY: "2G"
    volumes:
      - ./survival:/data
    restart: unless-stopped
    networks:
      - mc-network

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    container_name: playit-agent
    network_mode: host
    environment:
      SECRET_KEY: "0013a3826dc4e984acb46c118a4792f606e3f4def4444edbed5a6d657470c347"
    restart: unless-stopped

networks:
  mc-network:
    driver: bridge
